### ISSUE TITLE
Remove engine-api dependency from docker/docker/daemon

### ISSUE THREAD

**Issue by tonistiigi** [docker/engine-api#199]
There is a bottleneck for updating anything api facing in docker daemon after engine-api was separated out. Previously some aspects of it were discussed in https://github.com/docker/docker/issues/19957 . The gist of it is that for some changes in daemon, code needs to be changed in this repo although they can really only be tested with a daemon. Also, because of `docker/docker` vendors `engine-api` there is a delay on getting changes merged and possibility on different changes getting mixed up or bugfixes getting blocked by features.

My proposal is to remove `engine-api` dependancy from `docker/docker/daemon` pkg(also container, builder etc.). The `docker/docker/client` pkg would keep it's imports. Once the client binary is moved out of `docker/docker` repo, the main repo would not depend on API any more.

This change would mean the types that engine requires would be defined in `docker/docker` repo. For easier client side usage `engine-api` could redefine all the types with aliases or even keep exceptions if they should be needed for some backwards compatibility features. The `engine-api` would vendor one specific version of the types from `docker/docker`, not the other way like it is now. To keep the library size small we would keep the convention in `docker/docker` that we always define exported types in separate packages. 

The product on docker-engine is the HTTP API, not `engine-api`. So docker-engine should define the types that HTTP API is using.

**Comment by vdemeester** [comment]
@tonistiigi I like the idea for the long term :+1:. The first step is then to *backport* the daemon specific one in `docker/docker`, removing the dependency and then decide wether or not we want to vendor some or just re-define them.

**Comment by calavera** [comment]
Creating a cycled dependency doesn't sound any better to me, tbh.

**Comment by vdemeester** [comment]
@calavera `docker/docker` *"daemon"* struct and `docker/engine-api` struct could be completely independent, but yeah, we shouldn't create a cycled dependency.

**Comment by tonistiigi** [comment]
@calavera There is no cycled dependency. Client depends on engine-api and does not depend on daemon. Daemon does not depend on engine-api. Engine-api depends on types from daemon subpackages(optional but I think cleaner).

**Comment by duglin** [comment]
Seems like keeping 2 repos so that so tightly linked is a lot of work/pain for very little benefit - as we've seen.

If the client were a totally independent project and changes didn't propagate in both directions, and had its own life cycle, then perhaps this would be a good option. But in reality they're very linked and I don't see the benefit of trying to force a split.  As we've seen, many times, we end up with PRs in two repos and that causes pain and extra work - so let's just stop that.

IMO, we should move it all back to one repo with very clear pkg lines/boundaries, so that people can vendor at the appropriate spot (APIs, types, etc...) but allows for a single PR to introduce changes from CLI->API->types->Engine (and tests at CLI,integration) all in one shot - its so much easier to review/test that way.

**Comment by tonistiigi** [comment]
closed by docker/docker#26349
